// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright (c) Microsoft Corporation
//
// Author: Jon Lange <jlange@microsoft.com>

use crate::error::BootImageError;
use crate::page_tables::page_align_up;

use bootdefs::boot_params::BootParamBlock;

/// Page table self-map level 3 index
pub const PGTABLE_LVL3_IDX_PTE_SELFMAP: usize = 493;

/// An address span encoded as (base, length)
#[derive(Clone, Copy, Debug)]
pub struct BootImageSpan {
    pub start: u64,
    pub length: u64,
}

impl BootImageSpan {
    pub fn new(start: u64, length: u64) -> Self {
        Self { start, length }
    }
}

/// This is a structure generated by the boot image loader that contains the
/// execution context information required to launch the loaded boot image.
#[derive(Debug)]
pub struct BootImageContext {
    pub entry_point: u64,
    pub initial_stack: u64,
    pub paging_root: u64,
}

/// This structure is also generated by the boot image loader to describe
/// information about the boot image to that is needed to complete the
/// preparation of the boot image by the boot image host.
#[derive(Debug)]
pub struct BootImageInfo {
    pub context: BootImageContext,
    pub kernel_page_tables_base: u64,
    pub total_pt_pages: u64,
    pub kernel_launch_info: u64,
    pub boot_params_paddr: u64,
    pub cpuid_paddr: u64,
    pub secrets_paddr: u64,
    pub kernel_pdpt_paddr: u64,
    pub kernel_pml4e_index: u32,
}

/// This is a structure of kernel launch information that is generated by the
/// boot image host, which will be inserted into the kernel launch parameters
/// and mixed with launch parameters generated by the boot image builder.
#[derive(Debug)]
pub struct BootImageParams<'a> {
    pub kernel_region_start: u64,
    pub kernel_region_page_count: u64,
    pub stage2_start: u64,
    pub kernel_fs_start: u64,
    pub kernel_fs_end: u64,
    pub vtom: u64,
    pub boot_params: &'a BootParamBlock,
}

pub fn add_page_contents<F>(f: &mut F, paddr: u64, contents: &[u8]) -> Result<(), BootImageError>
where
    F: FnMut(u64, Option<&[u8]>, u64) -> Result<(), BootImageError>,
{
    f(paddr, Some(contents), page_align_up(contents.len() as u64))
}
