// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright (c) 2022-2023 SUSE LLC
//
// Author: Joerg Roedel <jroedel@suse.de>

extern crate alloc;

use crate::error::SvsmError;
use alloc::vec::Vec;
use core::mem;
use core::str::{self, Utf8Error};
use zerocopy::{FromBytes, Immutable, KnownLayout};

#[derive(Copy, Clone, Debug, Default, FromBytes, KnownLayout, Immutable)]
#[repr(C, packed)]
/// Raw header of an ACPI table. It corresponds to the beginning
/// portion of ACPI tables, before any specific table data
struct RawACPITableHeader {
    /// Signature specificies the type of ACPI table
    sig: [u8; 4],
    /// Length of the table
    len: u32,
    /// Revision (signature field)
    rev: u8,
    /// Checksum for data integrity
    chksum: u8,
    /// OEM-supplied string to identify OEM
    oem_id: [u8; 6],
    /// OEM-supplied string to identify tables
    oem_table_id: [u8; 8],
    /// OEM-supplied version number
    oem_rev: u32,
    /// ID for compiler
    compiler_id: [u8; 4],
    /// Revision of compiler used to create the table
    compiler_rev: u32,
}

#[derive(Debug, Default)]
/// Higher level representation of the raw ACPI table header
struct ACPITableHeader {
    sig: [u8; 4],
    len: u32,
    rev: u8,
    chksum: u8,
    oem_id: [u8; 6],
    oem_table_id: [u8; 8],
    oem_rev: u32,
    compiler_id: [u8; 4],
    compiler_rev: u32,
}

impl ACPITableHeader {
    /// Create a new [`ACPITableHeader`] from a raw [`RawACPITableHeader`].
    ///
    /// This constructor converts a raw ACPI table header into a higher-level [`ACPITableHeader`].
    ///
    /// # Arguments
    ///
    /// * `raw` - A [`RawACPITableHeader`] containing the raw header data.
    ///
    /// # Returns
    ///
    /// A new [`ACPITableHeader`] instance.
    const fn new(raw: RawACPITableHeader) -> Self {
        Self {
            sig: raw.sig,
            len: raw.len,
            rev: raw.rev,
            chksum: raw.chksum,
            oem_id: raw.oem_id,
            oem_table_id: raw.oem_table_id,
            oem_rev: raw.oem_rev,
            compiler_id: raw.compiler_id,
            compiler_rev: raw.compiler_rev,
        }
    }

    /// Print a human-readable summary of the ACPI table header's fields
    #[expect(dead_code)]
    fn print_summary(&self) -> Result<(), str::Utf8Error> {
        let sig = str::from_utf8(&self.sig)?;
        let oem_id = str::from_utf8(&self.oem_id)?;
        let oem_table_id = str::from_utf8(&self.oem_table_id)?;
        let compiler_id = str::from_utf8(&self.compiler_id)?;
        log::trace!(
            "ACPI: [{} {} {} {} {} {} {} {} {}]",
            sig,
            self.len,
            self.rev,
            self.chksum,
            oem_id,
            oem_table_id,
            self.oem_rev,
            compiler_id,
            self.compiler_rev
        );
        Ok(())
    }
}

#[derive(Debug)]
/// ACPI table, both header and contents
pub struct ACPITable<'a> {
    header: ACPITableHeader,
    /// Raw binary content of ACPI table
    buf: &'a [u8],
}

impl<'a> ACPITable<'a> {
    /// Create a new [`ACPITable`] from raw binary data.
    ///
    /// This constructor creates an [`ACPITable`] instance by parsing raw binary data.
    ///
    /// # Arguments
    ///
    /// * `ptr` - A slice containing the raw binary data of the ACPI table.
    ///
    /// # Returns
    ///
    /// A new [`ACPITable`] instance on success, or an [`SvsmError`] if parsing fails.
    pub fn new(ptr: &'a [u8]) -> Result<Self, SvsmError> {
        let (raw_header, _) =
            RawACPITableHeader::read_from_prefix(ptr).map_err(|_| SvsmError::Acpi)?;
        let size = raw_header.len as usize;
        let buf = ptr.get(..size).ok_or(SvsmError::Acpi)?;

        if !Self::verify_checksum(buf) {
            // Just print a warning and don't fail, since checksum is not relevant
            // for securlity (generated by hypervisor) and corruption is unlikely.
            let sig = str::from_utf8(&raw_header.sig).unwrap_or("????");
            log::warn!("ACPI: checksum mismatch for table '{sig}'");
        }

        let header = ACPITableHeader::new(raw_header);

        Ok(Self { header, buf })
    }

    /// Calculate and verify the ACPI table checksum of a raw data chunk
    ///
    /// # Arguments
    ///
    /// * `data` - Array containing the raw binary data of an ACPI table
    ///
    /// # Returns
    ///
    /// True, if the checksum is correct, False otherwise.
    fn verify_checksum(data: &[u8]) -> bool {
        data.iter().copied().fold(0, u8::wrapping_add) == 0
    }

    /// Get the signature of the ACPI table.
    ///
    /// This method returns the 4-character signature of the ACPI table, such as "APIC."
    #[expect(dead_code)]
    fn signature(&self) -> Result<&str, Utf8Error> {
        str::from_utf8(&self.header.sig)
    }

    /// Get the content of the ACPI table.
    ///
    /// This method returns a reference to the binary content of the ACPI table,
    /// excluding the header.
    ///
    /// # Returns
    ///
    /// A reference to the ACPI table content, or [`None`] if the content is empty.
    fn content(&self) -> Option<&[u8]> {
        let offset = mem::size_of::<RawACPITableHeader>();
        // Zero-length slices are valid, but we do not want them
        self.buf.get(offset..).filter(|b| !b.is_empty())
    }

    /// Get a pointer to the content of the ACPI table at a specific offset.
    ///
    /// This method returns a pointer to the content of the ACPI table at the specified offset,
    /// converted to the desired type `T`.
    ///
    /// # Arguments
    ///
    /// * `offset` - The offset at which to obtain the pointer.
    ///
    /// # Returns
    ///
    /// A reference to the content of the ACPI table at specified offset as type `T`,
    /// or [`None`] if the offset is out of bounds.
    fn content_ptr<T>(&self, offset: usize) -> Option<&T>
    where
        T: FromBytes + KnownLayout + Immutable,
    {
        let bytes = self.content()?.get(offset..)?;
        T::ref_from_prefix(bytes).ok().map(|(value, _rest)| value)
    }
}

const MADT_HEADER_SIZE: usize = 8;

/// Header of an entry within MADT
#[derive(Clone, Copy, Debug, FromBytes, Immutable, KnownLayout)]
#[repr(C, packed)]
struct RawMADTEntryHeader {
    entry_type: u8,
    entry_len: u8,
}

/// Entry for a local APIC within MADT
#[derive(Clone, Copy, Debug, FromBytes, Immutable, KnownLayout)]
#[repr(C, packed)]
struct RawMADTEntryLocalApic {
    header: RawMADTEntryHeader,
    acpi_id: u8,
    apic_id: u8,
    flags: u32,
}

/// Entry for a local X2APIC within MADT
#[derive(Clone, Copy, Debug, FromBytes, Immutable, KnownLayout)]
#[repr(C, packed)]
struct RawMADTEntryLocalX2Apic {
    header: RawMADTEntryHeader,
    reserved: [u8; 2],
    apic_id: u32,
    flags: u32,
    acpi_id: u32,
}

/// Information about an ACPI CPU
#[derive(Clone, Copy, Debug)]
pub struct ACPICPUInfo {
    /// The APIC ID for the CPU
    pub apic_id: u32,
    /// Indicates whether the CPU is enabled
    pub enabled: bool,
}

/// Loads ACPI CPU information by parsing the ACPI tables.
/// It processes the Multiple APIC Description Table (MADT) to extract information about each CPU's
/// APIC ID and enabled status.
///
/// # Arguments
///
/// * 'apic_table': A reference to the MADT that was located from the ACPI tables.
///
/// # Returns
///
/// A [`Result`] containing a vector of [`ACPICPUInfo`] structs representing CPU information.
/// If successful, the vector contains information about each detected CPU; otherwise, an error is returned.
///
/// # Errors
///
/// This function returns an error if there are issues with reading or parsing ACPI tables.
pub fn load_acpi_cpu_info(apic_table: &ACPITable<'_>) -> Result<Vec<ACPICPUInfo>, SvsmError> {
    let content = apic_table.content().ok_or(SvsmError::Acpi)?;
    let mut cpus: Vec<ACPICPUInfo> = Vec::new();

    let mut offset = MADT_HEADER_SIZE;
    while offset < content.len() {
        let entry_ptr = apic_table
            .content_ptr::<RawMADTEntryHeader>(offset)
            .ok_or(SvsmError::Acpi)?;
        let entry_len = usize::from(entry_ptr.entry_len);

        match entry_ptr.entry_type {
            0 if entry_len == mem::size_of::<RawMADTEntryLocalApic>() => {
                let lapic_ptr = apic_table
                    .content_ptr::<RawMADTEntryLocalApic>(offset)
                    .ok_or(SvsmError::Acpi)?;
                cpus.push(ACPICPUInfo {
                    apic_id: lapic_ptr.apic_id as u32,
                    enabled: (lapic_ptr.flags & 1) == 1,
                });
            }
            9 if entry_len == mem::size_of::<RawMADTEntryLocalX2Apic>() => {
                let x2apic_ptr = apic_table
                    .content_ptr::<RawMADTEntryLocalX2Apic>(offset)
                    .ok_or(SvsmError::Acpi)?;
                cpus.push(ACPICPUInfo {
                    apic_id: x2apic_ptr.apic_id,
                    enabled: (x2apic_ptr.flags & 1) == 1,
                });
            }
            madt_type if entry_len == 0 => {
                log::warn!("Found zero-length MADT entry with type {madt_type}, stopping");
                break;
            }
            madt_type => {
                log::info!("Ignoring MADT entry with type {madt_type}");
            }
        }

        offset = offset.checked_add(entry_len).ok_or(SvsmError::Acpi)?;
    }

    Ok(cpus)
}
