#!/bin/bash
#

RET=0

for file in `git diff --name-only --staged`; do
    ext=${file##*.}
    if [ "$ext" == "rs" ]; then
        rustfmt --unstable-features --check --edition 2021 --skip-children $file > /dev/null 2>&1
        if [ "$?" == "1" ]; then
            echo "$file needs rustfmt checking"
            RET=1
        fi
    fi
done

exit $RET
