#!/bin/bash
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Copyright (c) 2023 SUSE LLC
#
# Author: Joerg Roedel <jroedel@suse.de>

RET=0
CHECK_SPDX="$(git rev-parse --show-toplevel)/scripts/check-spdx.sh"

staged_files=$(git diff --diff-filter=d --name-only --staged)

for file in $staged_files; do
    ext=${file##*.}
    if [ "$ext" == "rs" ]; then
        rustfmt --check $file > /dev/null 2>&1
        if [ "$?" == "1" ]; then
            echo "$file needs rustfmt checking"
            RET=1
        fi
    fi
done

if [ -n "$staged_files" ]; then
    "$CHECK_SPDX" --files $staged_files || RET=1
fi

make clippy || exit 1

exit $RET

