// SPDX-License-Identifier: MIT
//
// Copyright (c) 2025 SUSE LLC
// Copyright (c) 2025 Advanced Micro Devices, Inc
//
// Author: Joerg Roedel <joerg.roedel@amd.com>

use std::fs::OpenOptions;
use std::io::prelude::*;
use std::process::Command;
use std::string::String;

const RELEASE_FILE: &str = "release/src/git_version.rs";

fn git_version() -> Result<String, ()> {
    let output = Command::new("git")
        .args(["describe", "--always", "--dirty=+"])
        .output()
        .map_err(|_| ())?;
    if !output.status.success() {
        return Err(());
    }

    let stdout = String::from_utf8(output.stdout).map_err(|_| ())?;
    let mut lines = stdout.lines();
    let first_line = lines.next().ok_or(())?.trim();
    // Strip leading `v` from git tag
    let version = first_line.strip_prefix("v").unwrap_or(first_line);
    Ok(String::from(version))
}

fn write_version(version: String) {
    let mut file = OpenOptions::new()
        .create(true)
        .write(true)
        .truncate(true)
        .open(RELEASE_FILE)
        .unwrap();
    writeln!(&mut file, "// SPDX-License-Identifier: MIT\n//").unwrap();
    writeln!(
        &mut file,
        "// This file is automatically generated - Any changes will be overwritten\n//\n"
    )
    .unwrap();
    writeln!(&mut file, "pub const GIT_VERSION: &str = \"{version}\";").unwrap();
}

pub fn generate_release_file() {
    write_version(git_version().unwrap_or_default());
}
